# NumPy

In [2]:
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [8]:
a=np.array([1,2,3,4,5])

# 1D array

In [9]:
a.dtype

dtype('int32')

In [10]:
a.size

5

In [11]:
a.shape

(5,)

In [12]:
a.ndim

1

In [13]:
a[0]

1

In [14]:
a[3]

4

# 2D array

In [34]:
b=np.array([[1,2,3],[5,6,6]])

In [35]:
b.dtype

dtype('int32')

In [20]:
b.size

2

In [21]:
b.ndim

1

In [22]:
b.shape

(2,)

In [24]:
b[0]

[1, 2, 3]

In [26]:
b[1]

[5, 6]

In [28]:
b[0][0]

1

In [29]:
b[0][2]

3

In [36]:
b

array([[1, 2, 3],
       [5, 6, 6]])

In [38]:
b.dtype

dtype('int32')

In [37]:
b

array([[1, 2, 3],
       [5, 6, 6]])

# multi dimensional array

In [40]:
c=np.array([[[[2,3]]]])

In [41]:
c

array([[[[2, 3]]]])

In [42]:
c.size

2

In [43]:
c.shape

(1, 1, 1, 2)

In [44]:
c.ndim

4

In [45]:
c.dtype

dtype('int32')

In [48]:
c[0][0]

array([[2, 3]])

In [56]:
d=np.array([[[1,2,3,4]]])

In [57]:
d

array([[[1, 2, 3, 4]]])

In [58]:
d.shape

(1, 1, 4)

In [59]:
d.ndim

3

In [62]:
d[0][0]

array([1, 2, 3, 4])

In [70]:
e=np.array([[[[[3]]]]])

In [71]:
e

array([[[[[3]]]]])

In [72]:
e.ndim

5

In [84]:
f=np.array([[[[[1,2,3,4],[2,3,4,5],[3,4,5,6],[4,5,6,7]]]]],dtype=float)

In [85]:
f

array([[[[[1., 2., 3., 4.],
          [2., 3., 4., 5.],
          [3., 4., 5., 6.],
          [4., 5., 6., 7.]]]]])

In [86]:
f.ndim

5

In [87]:
f.shape

(1, 1, 1, 4, 4)

In [88]:
f.size

16

In [89]:
f[0][0][0][1]

array([2., 3., 4., 5.])

## filling arrays

In [6]:
s=np.full((5,3,5,6),7)

In [100]:
s

array([[[[7, 7, 7, 7, 7, 7],
         [7, 7, 7, 7, 7, 7],
         [7, 7, 7, 7, 7, 7],
         [7, 7, 7, 7, 7, 7],
         [7, 7, 7, 7, 7, 7]],

        [[7, 7, 7, 7, 7, 7],
         [7, 7, 7, 7, 7, 7],
         [7, 7, 7, 7, 7, 7],
         [7, 7, 7, 7, 7, 7],
         [7, 7, 7, 7, 7, 7]],

        [[7, 7, 7, 7, 7, 7],
         [7, 7, 7, 7, 7, 7],
         [7, 7, 7, 7, 7, 7],
         [7, 7, 7, 7, 7, 7],
         [7, 7, 7, 7, 7, 7]]],


       [[[7, 7, 7, 7, 7, 7],
         [7, 7, 7, 7, 7, 7],
         [7, 7, 7, 7, 7, 7],
         [7, 7, 7, 7, 7, 7],
         [7, 7, 7, 7, 7, 7]],

        [[7, 7, 7, 7, 7, 7],
         [7, 7, 7, 7, 7, 7],
         [7, 7, 7, 7, 7, 7],
         [7, 7, 7, 7, 7, 7],
         [7, 7, 7, 7, 7, 7]],

        [[7, 7, 7, 7, 7, 7],
         [7, 7, 7, 7, 7, 7],
         [7, 7, 7, 7, 7, 7],
         [7, 7, 7, 7, 7, 7],
         [7, 7, 7, 7, 7, 7]]],


       [[[7, 7, 7, 7, 7, 7],
         [7, 7, 7, 7, 7, 7],
         [7, 7, 7, 7, 7, 7],
         [7, 7, 7, 7, 7, 7]

In [7]:
s.ndim

4

# zeros and ones

In [8]:
r=np.zeros((4,4))

In [9]:
r

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
v=np.ones((4,3,2))

In [11]:
v

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [12]:
v.ndim

3

In [13]:
v.shape

(4, 3, 2)

# empty and random

In [14]:
w=np.empty((3,3))

In [15]:
w

array([[4.67296746e-307, 1.69121096e-306, 8.01095173e-307],
       [6.23054293e-307, 2.22526399e-307, 6.23053614e-307],
       [7.56592338e-307, 9.34588061e-307, 3.62651150e-317]])

In [16]:
p=np.random.random((2,2))

In [17]:
p

array([[0.43559831, 0.22595591],
       [0.18104944, 0.38543059]])

In [18]:
p.ndim

2

In [19]:
p.size

4

# ranges 

In [20]:
q=np.arange(12,90,4)

In [21]:
q

array([12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64, 68, 72, 76,
       80, 84, 88])

# linspace

In [26]:
z=np.linspace(1,50,50)

In [27]:
z

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [28]:
z.size

50

In [31]:
z=np.linspace(0,50,13,dtype=int)

In [32]:
z

array([ 0,  4,  8, 12, 16, 20, 25, 29, 33, 37, 41, 45, 50])

# math function

In [4]:
a=np.array([10,20,30,40,50,60,70,80])

In [5]:
a

array([10, 20, 30, 40, 50, 60, 70, 80])

In [6]:
np.exp(a)

array([2.20264658e+04, 4.85165195e+08, 1.06864746e+13, 2.35385267e+17,
       5.18470553e+21, 1.14200739e+26, 2.51543867e+30, 5.54062238e+34])

In [37]:
np.sin(a)

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316, -0.26237485,
       -0.30481062,  0.77389068, -0.99388865])

In [38]:
np.cos(a)

array([-0.83907153,  0.40808206,  0.15425145, -0.66693806,  0.96496603,
       -0.95241298,  0.6333192 , -0.11038724])

In [39]:
np.tan(a)

array([ 0.64836083,  2.23716094, -6.4053312 , -1.11721493, -0.27190061,
        0.32004039,  1.22195992,  9.00365495])

In [7]:
np.log(a)

array([2.30258509, 2.99573227, 3.40119738, 3.68887945, 3.91202301,
       4.09434456, 4.24849524, 4.38202663])

In [8]:
np.sqrt(a)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781,
       7.74596669, 8.36660027, 8.94427191])

In [9]:
a.sum()

360

In [10]:
a.min()

10

In [11]:
a.mean()

45.0

In [14]:
np.median(a)

45.0

In [15]:
np.std(a)

22.9128784747792